---
name: 'Setup SOPS'
description: 'Install SOPS and age, configure decryption key'
inputs:
  age_secret_key:
    description: 'Age private key for decrypting secrets'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install age
      shell: bash
      run: |
        curl -sSL https://github.com/FiloSottile/age/releases/download/v1.2.0/age-v1.2.0-linux-amd64.tar.gz | sudo tar -xz -C /usr/local/bin --strip-components=1

    - name: Install SOPS
      shell: bash
      run: |
        curl -sSL https://github.com/getsops/sops/releases/download/v3.9.4/sops-v3.9.4.linux.amd64 -o /tmp/sops
        chmod +x /tmp/sops
        sudo mv /tmp/sops /usr/local/bin/sops

    - name: Configure age key
      shell: bash
      run: |
        mkdir -p ~/.config/sops/age
        printf '%s\n' "${{ inputs.age_secret_key }}" > ~/.config/sops/age/keys.txt
        chmod 600 ~/.config/sops/age/keys.txt
