creation_rules:
  # Kubernetes secrets
  - path_regex: secrets/kube\.yaml$
    age: >-
      AGE_PUBLIC_KEY_HERE

  # Default rule for any other secrets
  - path_regex: secrets/.*\.yaml$
    age: >-
      AGE_PUBLIC_KEY_HERE
