---
name: 'Setup SSH'
description: 'Configure SSH for Tailscale SSH (SSH keys optional as fallback)'
inputs:
  ssh_private_key:
    description: 'SSH private key for authentication (optional when using Tailscale SSH)'
    required: false
    default: ''
  ansible_vault_password:
    description: 'Ansible vault password (optional, only needed for Ansible jobs)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup SSH
      shell: bash
      run: |
        eval `ssh-agent -s`
        mkdir -p /home/runner/.ssh/

        # Configure SSH for Tailscale SSH
        # When Tailscale is running (via tailscale/github-action), SSH connections to Tailscale
        # hostnames automatically use Tailscale SSH authentication. No explicit ProxyCommand
        # or SSH key is needed - Tailscale handles authentication via its identity system.
        # This works because Tailscale intercepts SSH connections to Tailscale hostnames
        # when the Tailscale daemon is running.
        cat > /home/runner/.ssh/config << 'EOF'
        Host *
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
        EOF

        # Verify Tailscale is available (should be set up by tailscale/github-action)
        if ! command -v tailscale >/dev/null 2>&1; then
          echo "Warning: tailscale command not found. Tailscale SSH may not work."
        fi

        # Create Tailscale SSH wrapper script in the ansible directory
        # This ensures Ansible uses Tailscale SSH authentication instead of requiring SSH keys
        # The wrapper script checks for Tailscale and falls back to regular ssh
        # Works in GitHub Actions, local development, and self-hosted runners
        # The wrapper is created in the ansible directory so it's always available
        ANSIBLE_DIR="${{ github.workspace }}/ansible"
        WRAPPER_SCRIPT="$ANSIBLE_DIR/tailscale-ssh-wrapper"
        cat > "$WRAPPER_SCRIPT" << 'WRAPPER_EOF'
        #!/bin/bash
        # Universal wrapper script for Ansible to use Tailscale SSH when available
        # This script checks for Tailscale and falls back to regular ssh
        # Works in GitHub Actions, local development, and self-hosted runners

        # If tailscale is available and running, use it directly
        if command -v tailscale >/dev/null 2>&1 && tailscale status >/dev/null 2>&1; then
          exec tailscale ssh "$@"
        fi

        # Fallback to regular ssh
        exec ssh "$@"
        WRAPPER_EOF
        chmod +x "$WRAPPER_SCRIPT"
        # Add ansible directory to PATH so the wrapper can be found
        echo "$ANSIBLE_DIR" >> $GITHUB_PATH

        # Optionally set up SSH key as fallback if provided
        if [ -n "${{ inputs.ssh_private_key }}" ]; then
          echo -e "${{ inputs.ssh_private_key }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          # Add IdentityFile to config if key is provided
          echo "  IdentityFile ~/.ssh/id_rsa" >> /home/runner/.ssh/config
        fi

    - name: Setup Ansible Vault
      if: inputs.ansible_vault_password != ''
      shell: bash
      working-directory: ${{ github.workspace }}/ansible
      run: |
        # Create the Ansible Vault password file for decryption
        echo -e "${{ inputs.ansible_vault_password }}" > ./vault.pass
