---
name: 'Setup SSH'
description: 'Configure SSH for Tailscale SSH (SSH keys optional as fallback)'
inputs:
  ssh_private_key:
    description: 'SSH private key for authentication (optional when using Tailscale SSH)'
    required: false
    default: ''
  ansible_vault_password:
    description: 'Ansible vault password (optional, only needed for Ansible jobs)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup SSH
      shell: bash
      run: |
        eval `ssh-agent -s`
        mkdir -p /home/runner/.ssh/

        # Configure SSH for Tailscale SSH
        # When Tailscale is running (via tailscale/github-action), SSH connections to Tailscale
        # hostnames automatically use Tailscale SSH authentication. No explicit ProxyCommand
        # or SSH key is needed - Tailscale handles authentication via its identity system.
        # This works because Tailscale intercepts SSH connections to Tailscale hostnames
        # when the Tailscale daemon is running.
        cat > /home/runner/.ssh/config << 'EOF'
        Host *
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
        EOF

        # Verify Tailscale is available (should be set up by tailscale/github-action)
        if ! command -v tailscale >/dev/null 2>&1; then
          echo "Warning: tailscale command not found. Tailscale SSH may not work."
        fi

        # Create wrapper script for Ansible to use Tailscale SSH
        # This ensures Ansible uses Tailscale SSH authentication instead of requiring SSH keys
        mkdir -p /home/runner/.local/bin
        cat > /home/runner/.local/bin/tailscale-ssh-wrapper << 'WRAPPER_EOF'
        #!/bin/bash
        # Wrapper script to use tailscale ssh when available, fallback to regular ssh
        if command -v tailscale >/dev/null 2>&1 && tailscale status >/dev/null 2>&1; then
          exec tailscale ssh "$@"
        else
          exec ssh "$@"
        fi
        WRAPPER_EOF
        chmod +x /home/runner/.local/bin/tailscale-ssh-wrapper
        # Add to PATH so Ansible can find it
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

        # Optionally set up SSH key as fallback if provided
        if [ -n "${{ inputs.ssh_private_key }}" ]; then
          echo -e "${{ inputs.ssh_private_key }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          # Add IdentityFile to config if key is provided
          echo "  IdentityFile ~/.ssh/id_rsa" >> /home/runner/.ssh/config
        fi

    - name: Setup Ansible Vault
      if: inputs.ansible_vault_password != ''
      shell: bash
      working-directory: ${{ github.workspace }}/ansible
      run: |
        # Create the Ansible Vault password file for decryption
        echo -e "${{ inputs.ansible_vault_password }}" > ./vault.pass
