---
name: 'Setup SSH'
description: 'Configure SSH for Tailscale SSH connections'
runs:
  using: 'composite'
  steps:
    - name: Setup SSH
      shell: bash
      run: |
        mkdir -p /home/runner/.ssh/

        # Configure SSH for Tailscale SSH
        # When Tailscale is running (via tailscale/github-action), SSH connections to Tailscale
        # hostnames automatically use Tailscale SSH authentication. Regular 'ssh' is used -
        # Tailscale intercepts connections to Tailscale hostnames automatically.
        # No wrapper or special SSH executable needed.
        cat > /home/runner/.ssh/config << 'SSHEOF'
        Host *
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
        SSHEOF

        # Verify Tailscale is available (should be set up by tailscale/github-action)
        if ! command -v tailscale >/dev/null 2>&1; then
          echo "::error::tailscale command not found. Tailscale must be set up first."
          exit 1
        fi

        # Verify Tailscale is connected
        if ! tailscale status >/dev/null 2>&1; then
          echo "::error::Tailscale is not connected. Check tailscale/github-action setup."
          exit 1
        fi

        echo "✅ Tailscale is connected. SSH to Tailscale hostnames will work automatically."
