---
# Common role - base system configuration for all Raspberry Pis

- name: Install essential packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags: packages

