---
name: 'Setup Ansible Environment'
description: 'Install and configure Ansible, Tailscale, and run linters'
inputs:
  tailscale_client_id:
    description: 'Tailscale OAuth client ID'
    required: true
  tailscale_client_secret:
    description: 'Tailscale OAuth client secret'
    required: true

runs:
  using: 'composite'
  steps:
    # Setup Tailscale network on the Actions worker
    # Enables connection to nodes via Tailscale SSH (no SSH keys needed)
    - name: Tailscale
      uses: tailscale/github-action@v4.1.1
      with:
        oauth-client-id: ${{ inputs.tailscale_client_id }}
        oauth-secret: ${{ inputs.tailscale_client_secret }}
        tags: tag:k3s

    - name: Set up Python 3.x
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: |
          .pre-commit-config.yaml
          ansible/requirements.yml

    - name: Install ansible-core and ansible-lint
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        pip3 install 'ansible-core==2.20.0rc2' ansible-lint

    - name: Cache Ansible collections
      uses: actions/cache@v5
      with:
        path: ~/.ansible/collections
        key: ${{ runner.os }}-ansible-collections-${{ hashFiles('ansible/requirements.yml') }}
        restore-keys: |
          ${{ runner.os }}-ansible-collections-

    - name: Install Ansible collections
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        set -euo pipefail
        # Work around Galaxy metadata 500s by installing from artifact URLs.
        ansible-galaxy collection install \
          "https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/ansible-posix-2.1.0.tar.gz" \
          --force
        ansible-galaxy collection install \
          "https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-general-12.2.0.tar.gz" \
          --force
        tmp_requirements="$(mktemp)"
        awk '
          $0 ~ /^  - name: ansible\.posix$/ {skip=1; next}
          $0 ~ /^  - name: community\.general$/ {skip=1; next}
          skip && $0 ~ /^  - name:/ {skip=0}
          !skip {print}
        ' ansible/requirements.yml > "$tmp_requirements"
        ansible-galaxy collection install -r "$tmp_requirements" --force

    - name: Run ansible-lint
      shell: bash
      working-directory: ansible
      run: ansible-lint

    - name: Setup SSH
      uses: ./.github/actions/setup-ssh
