---
name: 'Setup Ansible Environment'
description: 'Install and configure Ansible, Tailscale, and run linters'
inputs:
  tailscale_client_id:
    description: 'Tailscale OAuth client ID'
    required: true
  tailscale_client_secret:
    description: 'Tailscale OAuth client secret'
    required: true
  ansible_vault_password:
    description: 'Ansible vault password for decrypting files'
    required: true

runs:
  using: 'composite'
  steps:
    # Setup Tailscale network on the Actions worker
    # Enables connection to nodes via Tailscale SSH (no SSH keys needed)
    - name: Tailscale
      uses: tailscale/github-action@v4.1.0
      with:
        oauth-client-id: ${{ inputs.tailscale_client_id }}
        oauth-secret: ${{ inputs.tailscale_client_secret }}
        tags: tag:k3s

    - name: Set up Python 3.x
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: |
          .pre-commit-config.yaml
          ansible/requirements.yml

    - name: Install ansible-core and ansible-lint
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        pip3 install 'ansible-core==2.20.0rc2' ansible-lint

    - name: Cache Ansible collections
      uses: actions/cache@v4
      with:
        path: ~/.ansible/collections
        key: ${{ runner.os }}-ansible-collections-${{ hashFiles('ansible/requirements.yml') }}
        restore-keys: |
          ${{ runner.os }}-ansible-collections-

    - name: Install Ansible collections
      shell: bash
      working-directory: ${{ github.workspace }}
      run: ansible-galaxy collection install -r ansible/requirements.yml --force

    - name: Run ansible-lint
      shell: bash
      working-directory: ansible
      run: ansible-lint

    - name: Setup SSH
      uses: ./.github/actions/setup-ssh
      with:
        ansible_vault_password: ${{ inputs.ansible_vault_password }}
