# from https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd#ha-mode-with-autoscaling
redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  additionalApplications:
    - destination:
        namespace: "default"
        server: "https://kubernetes.default.svc"
      finalizers:
        - "resources-finalizer.argocd.argoproj.io"
      name: "app-of-apps"
      namespace: "argo-cd"
      project: "default"
      source:
        directory:
          recurse: true
        path: "."
        repoURL: "https://github.com/slashr/app-manifests.git"
        targetRevision: "main" #should correspond to the active branch name

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

configs:
  repositories:
    podinfo-helm-repo:
      url: https://stefanprodan.github.io/podinfo
      name: podinfo
      type: helm
    app-manifests-repo:
      url: https://github.com/slashr/app-manifests.git
      name: app-manifests
      type: git
