apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-wildcard
  namespace: ${namespace}
spec:
  secretName: cert-wildcard
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '*.${cluster_base_url}'
  dnsNames:
  - ${cluster_base_url}
  - '*.${cluster_base_url}'
%{ for extra_domain in extra_cluster_domains  ~}
  - '*.${extra_domain}'
  - '${extra_domain}'
%{ endfor ~}
  