# -- _Kubernetes_ resources to monitor for DNS entries.
sources:
  - ingress

provider: 
  name: cloudflare

domainFilters:
  - akashnair.com
  - shrub.dev

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token-secret
        key: api-token
