---
name: 'Setup and Run Pre-commit'
description: 'Install pre-commit, cache it, and run checks on changed files'
runs:
  using: 'composite'
  steps:
    - name: Set up Python for pre-commit
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: '.pre-commit-config.yaml'

    - name: Install pre-commit
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pre-commit

    - name: Cache pre-commit environments
      uses: actions/cache@v5
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Cache pre-commit hook repositories
      uses: actions/cache@v5
      with:
        path: ~/.cache/pre-commit/repo*
        key: ${{ runner.os }}-pre-commit-repos-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
        else
          BASE_SHA="${{ github.event.before }}"
        fi

        # Handle workflow_dispatch or initial pushes where BASE_SHA is empty or all zeros
        if [ -z "$BASE_SHA" ] || [ "$BASE_SHA" = "0000000000000000000000000000000000000000" ]; then
          echo "No base SHA available (workflow_dispatch or initial push), running on all files in workspace"
          CHANGED_FILES=""
        else
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACM "$BASE_SHA" "${{ github.sha }}")
        fi

        # Skip terraform hooks if terraform is not installed
        SKIP_HOOKS=""
        if ! command -v terraform &> /dev/null && ! command -v tofu &> /dev/null; then
          SKIP_HOOKS="terraform_fmt,terraform_validate"
          echo "Terraform/OpenTofu not found, skipping terraform hooks"
        fi

        if [ -n "$CHANGED_FILES" ]; then
          SKIP=$SKIP_HOOKS pre-commit run --files $CHANGED_FILES --hook-stage manual
        else
          echo "No changed files to check, skipping pre-commit"
        fi
