---
# Handlers for network configuration changes

- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
  become: true

- name: Restart dhcpcd
  ansible.builtin.systemd:
    name: dhcpcd
    state: restarted
  become: true

- name: Restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
  become: true

