controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: false
    minReplicas: 1
  additionalApplications:
    - destination:
        namespace: "default"
        server: "https://kubernetes.default.svc"
      name: "app-of-appss"
      project: "default"
      namespace: "argo-cd"
      source:
        directory:
          recurse: true
        path: "."
        repoURL: "https://github.com/slashr/app-manifests.git"
        targetRevision: "main" #should correspond to the active branch name


## The following addons are not really necessarily for a homelab setup
## Enable if you have enough CPU/Memory resources and need them for some purpose 
dex:
  enabled: false

redis:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: false

repoServer:
  autoscaling:
    enabled: false
    minReplicas: 1

configs:
  secret:
    argocdServerAdminPassword: $2a$10$6Oa1o/Y/5xjDk2dQCQ8F9uDCqm9w8BJEp7ZjI0.SvmZqIXXpHFyQW
  repositories:
    podinfo-helm-repo:
      url: https://stefanprodan.github.io/podinfo
      name: podinfo
      type: helm
    app-manifests-repo:
      url: https://github.com/slashr/app-manifests.git
      name: app-manifests
      type: git
