on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

# Add concurrency control to prevent conflicting deployments
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gcp-setup:
    name: "Setup GCP Infra"
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Add timeout to prevent hanging jobs
    defaults:
      run:
        working-directory: ./gcp
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: "1.9.6" # Pin Terraform version

      # Add caching for Terraform plugins
      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/gcp/.terraform.lock.hcl') }}
          restore-keys: ${{ runner.os }}-terraform-

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      # Save plan as artifact for review
      - name: Save Terraform Plan
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: gcp-terraform-plan
          path: ./gcp/terraform.tfplan
          retention-days: 5

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

  # Extract common SSH setup into a reusable composite action or use OIDC for authentication
  setup-ssh:
    name: "Setup SSH and Tailscale"
    runs-on: ubuntu-latest
    outputs:
      ssh_config: ${{ steps.ssh.outputs.ssh_config }}
    steps:
      - name: Setup SSH
        id: ssh
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          echo -e "${{secrets.SSH_AUTH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > /home/runner/.ssh/config
          echo "ssh_config=done" >> $GITHUB_OUTPUT

      - name: Tailscale
        uses: tailscale/github-action@v3.2.2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:k3s

  oracle-setup:
    name: "Setup Oracle Infra"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./oracle
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Setup Terraform variables
        id: vars
        run: |-
          cat > terraform.tfvars <<EOF
          user_ocid = "${{ secrets.TF_USER_OCID }}"
          tenancy_ocid = "${{ secrets.TF_TENANCY_OCID }}"
          ssh_authorized_keys = "${{ secrets.TF_SSH_AUTHORIZED_KEYS }}"
          oci_private_key = "${{ secrets.TF_OCI_PRIVATE_KEY }}"
          fingerprint = "${{ secrets.TF_FINGERPRINT }}"
          compartment_id = "${{ secrets.TF_COMPARTMENT_ID }}"
          EOF

      - name: "Terraform Plan"
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false



  tailscale-setup:
    name: "Setup Tailscale Network" 
    needs: [oracle-setup, gcp-setup, setup-ssh]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          submodules: true

      # Setup Tailscale network on the Actions worker
      # Enables connection to k3s nodes using Tailscale public IP
      - name: Tailscale
        uses: tailscale/github-action@v3.2.2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:k3s
    
      - name: Set up Python 3.7.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible-lint ansible

      - name: Run ansible-lint.
        run: ansible-lint

      - name: Setup SSH
        shell: bash
        run: |
         eval `ssh-agent -s`
         mkdir -p /home/runner/.ssh/
         touch /home/runner/.ssh/id_rsa
         # Create the SSH Private Key used to connect to all the servers using the Secret
         echo -e "${{secrets.SSH_AUTH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
         # Create the Ansible Vault password file for decryption
         echo -e "${{secrets.ANSIBLE_VAULT_PASSWORD}}" > ./vault.pass
         chmod 700 /home/runner/.ssh/id_rsa
         # Disable strict host key checking
         echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > /home/runner/.ssh/config

      - name: Run vpn-playbook
        run: |
          ansible-playbook --private-key /home/runner/.ssh/id_rsa -i hosts.ini vpn.yml --vault-password-file ./vault.pass

  k3s-setup:
    name: "Setup K3S Cluster"
    needs: [tailscale-setup]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          submodules: true

      # Setup Tailscale network on the Actions worker
      # Enables connection to k3s nodes using Tailscale public IP
      - name: Tailscale
        uses: tailscale/github-action@v3.2.2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:k3s

      - name: Set up Python 3.7.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible-lint ansible

      - name: Run ansible-lint.
        run: ansible-lint

      - name: Setup SSH
        shell: bash
        run: |
         eval `ssh-agent -s`
         mkdir -p /home/runner/.ssh/
         touch /home/runner/.ssh/id_rsa
         # Create the SSH Private Key used to connect to all the servers using the Secret
         echo -e "${{secrets.SSH_AUTH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
         # Create the Ansible Vault password file for decryption
         echo -e "${{secrets.ANSIBLE_VAULT_PASSWORD}}" > ./vault.pass
         chmod 700 /home/runner/.ssh/id_rsa
         # Disable strict host key checking
         echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > /home/runner/.ssh/config

      - name: Run k3s-playbook
        env:
          TAILSCALE_JOIN_KEY: ${{ secrets.TAILSCALE_JOIN_KEY }}
        run: |
          ansible-playbook --private-key /home/runner/.ssh/id_rsa -i hosts.ini k3s.yml --vault-password-file ./vault.pass

  run-k3s:
    name: "Run Kubernetes Cluster"
    needs: [tailscale-setup, k3s-setup]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kubernetes
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Setup Terraform variables
        id: vars
        run: |-
          cat > terraform.tfvars <<EOF
          cloudflare_api_token = "${{ secrets.TF_CLOUDFLARE_API_TOKEN }}"
          kube_client_cert = "${{ secrets.TF_KUBE_CLIENT_CERT }}"
          kube_client_key = "${{ secrets.TF_KUBE_CLIENT_KEY }}"
          EOF

      - name: "Terraform Plan"
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      # Add drift detection
      - name: Check for Infrastructure Drift
        id: drift_check
        run: |
          terraform plan -detailed-exitcode -out=plan.tfplan
          echo "drift_exitcode=$?" >> $GITHUB_OUTPUT
      
      # Add plan summary for PRs
      - name: Terraform Plan Summary
        if: github.event_name == 'pull_request'
        run: |
          echo "## Terraform Plan Summary" >> $GITHUB_STEP_SUMMARY
          echo "* Resources to add: $(terraform show -json plan.tfplan | jq '.resource_changes | map(select(.change.actions[0] == "create")) | length')" >> $GITHUB_STEP_SUMMARY
          echo "* Resources to change: $(terraform show -json plan.tfplan | jq '.resource_changes | map(select(.change.actions[0] == "update")) | length')" >> $GITHUB_STEP_SUMMARY
          echo "* Resources to destroy: $(terraform show -json plan.tfplan | jq '.resource_changes | map(select(.change.actions[0] == "delete")) | length')" >> $GITHUB_STEP_SUMMARY
