on: [push]
jobs:
  terraform-validate:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    steps:
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform variables
        id: vars
        run: |-
          cat > terraform.tfvars <<EOF
          cloudflare_api_token = "${{ secrets.TF_CLOUDFLARE_API_TOKEN }}"
          kube_client_cert = "${{ secrets.TF_KUBE_CLIENT_CERT }}"
          kube_client_key = "${{ secrets.TF_KUBE_CLIENT_KEY }}"
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        
      - name: Terraform Validate
        run: terraform validate

  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform variables
        id: vars
        run: |-
          cat > terraform.tfvars <<EOF
          cloudflare_api_token = "${{ secrets.TF_CLOUDFLARE_API_TOKEN }}"
          kube_client_cert = "${{ secrets.TF_KUBE_CLIENT_CERT }}"
          kube_client_key = "${{ secrets.TF_KUBE_CLIENT_KEY }}"
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: terraform-plan
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
