on: [push]
jobs:
  Terraform-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.TF_CLOUDFLARE_API_TOKEN }}
          TF_VAR_kube_client_cert: ${{ secrets.TF_KUBE_CLIENT_CERT }}
          TF_VAR_kube_client_key: ${{ secrets.TF_KUBE_CLIENT_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
      - run: terraform init
      - id: plan
        run: terraform plan -no-color
